### ISSUE TITLE
Kindly provide CDN in the future.

### ISSUE THREAD

**Issue by ljfreelancer88** [BRIXTOL/pjax#11]
Hi, you used `pnpm` in the documentation. Is it possible to provide a CDN too. Thank You in advance.

**Comment by panoply** [comment]
Hey, you can just use an unpkg CDN which automatically generates and endpoint, eg: https://unpkg.com/@brixtol/pjax

PRs are welcome!

**Comment by ljfreelancer88** [comment]
Thank you! I have a follow up question.
Is this backed by a company?

**Comment by panoply** [comment]
It is used internally and externally by us on various projects. Not necessarily _backed_ per-say but our operations are highly dependant upon it. The module is released under this organization because I developed it specifically for us.
